name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt update
    - run: sudo apt install -y chrpath diffstat
    - run: sudo pip3 install kas
    - run: kas checkout kas-jpos-ci.yaml
    - run: kas build kas-jpos-ci.yaml
